import {
    AboutSlint,
    Button,
    VerticalBox,
    StandardTableView,
    TextEdit,
    TabWidget,
} from "std-widgets.slint";

component ScanResults inherits Rectangle {
    min-width: 500px;
    min-height: 200px;
    VerticalLayout {
    StandardTableView {
        columns: [
            { title: "Address", min-width: 50px },
            { title: "RSSI" },
            { title: "Name" },
            { title: "Data" },
        ];
        rows: [
            [ {text: "A"}, {text: "B"}, {text: "C"}, {text: "D"}],
        ];
    }}
}

export component AppWindow inherits Window {
    VerticalLayout {
        HorizontalLayout {
            VerticalLayout {
                alignment: start;
                padding: 10px;
                spacing: 10px;
                max-width: 100px;
                Button {
                    text: "Start scan";
                }

                Button {
                    text: "Stop scan";
                }

                Button {
                    text: "Connect";
                }

                Button {
                    text: "Bond";
                }

                Button {
                    text: "Disconnect";
                }
            }

            VerticalLayout {
                padding: 10px;
                spacing: 10px;
                TabWidget {
                    Tab {
                        title: "Scan results";
                        ScanResults {
                         }
                    }

                    Tab {
                        title: "Device A";
                        Rectangle {
                            min-height: 200px;
                            background: orange;
                        }
                    }
                }

                TextEdit {
                    min-height: 100px;
                    font-size: 12px;
                    text: "this is a log line\n and another";
                }
            }
        }
    }
}
